runtime: nodejs22
service: backend

readiness_check:
  path: "/readiness_check"
  check_interval_sec: 5
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2
  app_start_timeout_sec: 300

env_variables:
  SECRET_KEY: "goedanginssht"
  DB_HOST: "34.101.96.242"  # Atau gunakan alamat IP atau hostname jika di deploy di GCP
  DB_USER: "root"
  DB_PASSWORD: "iniPunyaKu!"  # Pastikan ini aman dan tidak disebarkan
  DB_NAME: "generalDB"

handlers:
  - url: /static
    static_dir: static/
  - url: /.*
    script: auto

# automatic_scaling:
#   min_num_instances: 1
#   max_num_instances: 15
#   cool_down_period_sec: 180
#   cpu_utilization:
#     target_utilization: 0.6
#   target_concurrent_requests: 100
